export const players = [
  { name: "Alvaro Santista", skill: 4.0, goalkeeper: false },
  { name: "Renato", skill: 4.0, goalkeeper: false },
  { name: "Vinícius Barba", skill: 3.0, goalkeeper: false },
  { name: "Robson Mosquito", skill: 3.0, goalkeeper: false },
  { name: "Murilo", skill: 4.0, goalkeeper: false },
  { name: "Deja", skill: 3.0, goalkeeper: false },
  { name: "Renan", skill: 4.0, goalkeeper: false },
  { name: "Erick Cebola", skill: 3.0, goalkeeper: false },
  { name: "Paulo Barba", skill: 2.0, goalkeeper: false },
  { name: "Iago (filho Deja)", skill: 2.0, goalkeeper: false },
  { name: "Carlos", skill: 2.0, goalkeeper: false },
  { name: "Henrique", skill: 3.0, goalkeeper: false },
  { name: "Victor Negão", skill: 4.0, goalkeeper: false },
  { name: "Lucas Fumaça", skill: 3.0, goalkeeper: false },
  { name: "Diego", skill: 4.5, goalkeeper: false },
  { name: "Araos (Diego Carlos)", skill: 5.0, goalkeeper: false },
  { name: "Menduba", skill: 5.0, goalkeeper: false },
  { name: "Cuesta", skill: 2.0, goalkeeper: false },
  { name: "Paulo (Pedro) (amigo Fabiano)", skill: 3.0, goalkeeper: false },
  { name: "Erivelton", skill: 3.5, goalkeeper: false },
  { name: "Ivan", skill: 4.0, goalkeeper: false },
  { name: "Eduardo Lopes", skill: 4.0, goalkeeper: false },
  { name: "Rafa Morais (binladen)", skill: 3.0, goalkeeper: false },
  { name: "pedroapp (alemao)", skill: 5.0, goalkeeper: false },
  { name: "Teló (daniel)", skill: 3.0, goalkeeper: false },
  { name: "Periclao", skill: 2.0, goalkeeper: false },
  { name: "Fabiano", skill: 3.0, goalkeeper: false },
  { name: "Tanque (amigo Rafa morais)", skill: 4.0, goalkeeper: false },
  { name: "Lucas Fonseca (amigo fabiano)", skill: 2.0, goalkeeper: false },
  { name: "Lucas Tolentino (amigo fabiano)", skill: 3.0, goalkeeper: false },
  { name: "Enzo", skill: 3.0, goalkeeper: false },
  { name: "Marcelo (amigo renan) (harry)", skill: 3.0, goalkeeper: false },
  { name: "Barreto", skill: 4.0, goalkeeper: true },
  { name: "Zé", skill: 5.0, goalkeeper: true },
  { name: "Daniel", skill: 4.0, goalkeeper: true },
  { name: "Guilherme", skill: 3.0, goalkeeper: true },
  { name: "Paulo Henrique(amigo menduba)", skill: 3.0, goalkeeper: true },
  { name: "Fletcher", skill: 3.0, goalkeeper: true },
].sort((a, b) => a.name.localeCompare(b.name));
